### ISSUE TITLE
Error, while make test

### ISSUE THREAD

**Issue by greno4ka** [mpereira/tty-solitaire#14]
Hello, I made "make test" and got error:

ttysolitaire_test: tests/game_test.c:132: test_valid_move_from_waste_pile_to_foundation_stacks: Assertion `valid_move(waste_pile, foundation_stacks[i])' failed.
make: *** [test] Aborted

**Comment by mpereira** [comment]
I get the same. There's a few tests that I think broke with some changes applied last year. I'll try to take a look at them soon.

**Comment by greno4ka** [comment]
So, yesterday, I looked at them and fixed stack_tests.c. But the second problem is in function valid_move, as I think. I can prepare PR, that fixes 2 tests and showing mistakes in other 5 tests in game_tests.c

I really cant understand what is happening in valid move verification. In such functions it's better to comment some blocks of code, what exactly happens there.

**Comment by porridge** [comment]
@mpereira this sort of blocks me from creating a Debian package, because unit tests are ran by default, and I'd rather not disable them if there is a waiting, working fix already... can you merge it?

**Comment by mpereira** [comment]
@porridge I noticed that the PR fixing `make test` touches the game code slightly, so I wanted to take a careful look into it before merging. I'll try to do it this week and will ping you.

**Comment by mpereira** [comment]
This was fixed by #35, and released on [tty-solitaire 1.2.0](https://github.com/mpereira/tty-solitaire/releases/tag/v1.2.0).

@porridge would you be able take another go at the Debian package?
