### ISSUE TITLE
Automatically detect "win" scenario

### ISSUE THREAD

**Issue by mpereira** [mpereira/tty-solitaire#17]
When both the stock and waste pile stacks are empty the game should automatically end.

**Comment by greno4ka** [comment]
And also all cards should be exposed! Now, I'am preparing PR for this issue.

**Comment by mpereira** [comment]
@greno4ka nice! I'll try to get some time this weekend to incorporate all your work.

**Comment by greno4ka** [comment]
I stucked on moment, how to detect that all cards are exposed=(( Going through all maneuvre[i] not work.. I ll try to see it more careful on these evenings..

**Comment by greno4ka** [comment]
When you will have time too see my PR? It's half of a year past!

**Comment by greno4ka** [comment]
Yeah, I've got the same problems, but I think I ll have time to contribute something in next month. I want to see a new release of tty-solitaire this year=)

**Comment by mpereira** [comment]
Sounds good, I'll cut a new release after we get the PRs merged.

**Comment by greno4ka** [comment]
Ping?=)

**Comment by greno4ka** [comment]
Vote for closing this issue, because fix PR was merged=)

**Comment by mpereira** [comment]
Sounds good. I cut a [new release](https://github.com/mpereira/tty-solitaire/releases/tag/v1.1.0) with your changes and pushed a [CHANGELOG file](https://github.com/mpereira/tty-solitaire/blob/master/CHANGELOG.org) too.

Thanks for your contributions!
