### ISSUE TITLE
Automatically detect "fail" scenario

### ISSUE THREAD

**Issue by greno4ka** [mpereira/tty-solitaire#25]
I think it's rather complex, but cool idea - to detect situations, when there is no solution to win the game. And program can draw a beautiful window with text "You're loser, lol, hahaha" or just "You lost"=)) But it will require some artificial intelligence.

**Comment by tisaconundrum2** [comment]
Not really artificial intelligence, but at least something to detect the state of the board and what is playable.

**Comment by greno4ka** [comment]
Pull requests are welcome!

**Comment by mpereira** [comment]
Closed by https://github.com/mpereira/tty-solitaire/pull/23.

**Comment by greno4ka** [comment]
So, the main problem in this situation is that we can bring card from foundation stack to maneuvres. Or I can misunderstand the terminology. So first of all it can be useful to create feature something like "hint how can I move card". And here, as I think, we have a problem with function valid_move, that dont pass the tests=((
