### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by cr6git** [mpereira/tty-solitaire#27]
Hi,

I would like to create a package for Void linux.
According to the [README](https://github.com/mpereira/tty-solitaire/blob/master/README.md#license) the license is MIT, but there's no LICENSE file.
Please add it.

Thanks.

**Comment by greno4ka** [comment]
Is licence file nessesary for packaging program in your distibution? I am packager of tty-solitaire in ALT Linux and I have no problems with this missing file.

**Comment by cr6git** [comment]
@greno4ka Yes, it is necessary to add the license file. Without it, I can't pass the check on Travis:
````
$ xlint srcpkgs/tty-solitaire/template
srcpkgs/tty-solitaire/template:10: license 'MIT', but no use of vlicense
````

**Comment by mpereira** [comment]
@cr6git done: https://github.com/mpereira/tty-solitaire/commit/3295098fa4c75d57b22909c4caf382c59f931c5f

Do you need us to cut a new release?

**Comment by greno4ka** [comment]
@mpereira Please correct the licence file, as I commented on your commit!

**Comment by cr6git** [comment]
I think it's okay now! :+1: 
Thank you.

**Comment by mpereira** [comment]
You're welcome!

**Comment by cr6git** [comment]
When the package will be built...
to install it in Void linux, you have to run: `xbps-install -S tty-solitaire`
