### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by Baggypants** [mpereira/tty-solitaire#30]
Fedora packaging guidelines recommend that the license the software under should be provided with the source code

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text

**Comment by Baggypants** [comment]
Note: it's missing from the release tagged as 1.1.0

**Comment by greno4ka** [comment]
Dublicate #27 

@mpereira maybe it's possible to make new release?

**Comment by mpereira** [comment]
Hi @Baggypants,

Thanks for bringing this to our attention. I'll create a new release soon.

**Comment by mpereira** [comment]
Released [v1.1.1](https://github.com/mpereira/tty-solitaire/releases/tag/v1.1.1).
