### ISSUE TITLE
make test fails on Debian Bullseye

### ISSUE THREAD

**Issue by vaporup** [mpereira/tty-solitaire#38]
~/Downloads/tty-solitaire-1.1.1 $ make test

ttysolitaire_test: tests/game_test.c:133: test_valid_move_from_waste_pile_to_foundation_stacks: Assertion `valid_move(waste_pile, foundation_stacks[i])' failed.
make: *** [Makefile:52: test] Aborted

**Comment by greno4ka** [comment]
Duplicates #14.

**Comment by mpereira** [comment]
Thanks for the report @vaporup. Let's consolidate this issue at #14 as @greno4ka pointed out.

**Comment by mpereira** [comment]
This was fixed by #35, and released on [tty-solitaire 1.2.0](https://github.com/mpereira/tty-solitaire/releases/tag/v1.2.0).
