### ISSUE TITLE
About detecting failure

### ISSUE THREAD

**Issue by GOKOP** [mpereira/tty-solitaire#48]
So I've noticed that an issue about this is open - this is odd because I was sure that the feature is already implemented. Specifically I'm talking about how the O on the stack changes to X. That's what this issue was supposed to be about - I'm in a situation where I'd expect this to happen but it doesn't. [Here's a screenshot](https://imgur.com/GAtyAZC)

So how is the state of failure detection? Is it partially implemented? Or does that X mean something completely different? Also, is my situation from the screenshot actually a game over or I'm missing something?

**Comment by mpereira** [comment]
Hi @GOKOP,

The `X` on the stack means that there's no more passes through the deck left. You can see the logic here: https://github.com/mpereira/tty-solitaire/blob/ff368bc980489a7cd0aed647e9f2159220610e89/src/gui.c#L81-L85

There's currently no logic in the game to detect an unwinnable scenario.

**Comment by GOKOP** [comment]
So is the fact that on my screenshot it shows an O even though there are no more cards a bug? Also thanks lol, I wonder how many games I've abandoned because I've thought I've lost

**Comment by mpereira** [comment]
> So is the fact that on my screenshot it shows an O even though there are no more cards a bug? 

The "O" means that pressing spacebar on it will move all cards on the waste pile back to the stack, giving the player another pass through the deck. By default, there are three passes. The "O" will become an "X" when the player has been three times through the deck.

> Also thanks lol, I wonder how many games I've abandoned because I've thought I've lost

No worries!
