### ISSUE TITLE
card don't show symbols

### ISSUE THREAD

**Issue by qvieth** [mpereira/tty-solitaire#59]
![image](https://user-images.githubusercontent.com/71810726/126872436-67c1ee18-9f2d-40c4-b705-f66807726d20.png)
I installed the app with nix on fedora, cards don't show symbols, anyone knows why?

**Comment by qvieth** [comment]
Installing with linux-brew fixes the issue

**Comment by mpereira** [comment]
Good to hear, thanks for reporting back!

**Comment by qvieth** [comment]
Thanks for making this awesome app !!
